### ISSUE TITLE
Could you share how you managed to get this GPT-related data from SimilarWeb?

### ISSUE THREAD

**Issue by kunhai-88** [1mrat/gpt-stats#1]
Hello! I noticed that you shared some GPT stats data pulled from SimilarWeb, and I'm really intrigued by it. I'm working on something similar right now, so I'm super interested in learning about your data scraping process. Could you share how you managed to get this GPT-related data from SimilarWeb? I'd really appreciate any insights or tips you can provide. Thanks a lot for sharing and for your help!

**Comment by 1mrat** [comment]
They have a popular pages feature which captures traffic share % of frequently visited URLs. 

more info here
https://support.similarweb.com/hc/en-us/articles/360019377337-Discover-Popular-Pages

**Comment by kunhai-88** [comment]
Thanks a lot!

**Comment by casssapir** [comment]
Thanks! Do you know if they offer cheaper subscriptions than the lowest level $125/mo option? Or if there are alternative providers of similar data ?

**Comment by 1mrat** [comment]
No - their subscription  is now very very expensive. I have an old legacy subscription thats still affordable but not sure how long it will last....
