### ISSUE TITLE
Thanks for the data, I have matched it at https://mygpts.dev/popular

### ISSUE THREAD

**Issue by savokiss** [1mrat/gpt-stats#3]
I've made a simple GPTs collection website for learning use, just added your stats data here:

<https://mygpts.dev/popular>

<img width="1291" alt="image" src="https://github.com/1mrat/gpt-stats/assets/5608189/7f76a384-6abf-442d-8173-6de49658a916">

I would like to add this repository or your blog to my site for reference, as you wish.

If there is anything inappropriate, you can close this issue. 😉

**Comment by 1mrat** [comment]
added to new tools page. Thanks.
