### ISSUE TITLE
Added gpt-stats to free public API and database of all GPTs

### ISSUE THREAD

**Issue by casssapir** [1mrat/gpt-stats#5]
Thanks @1mrat for pioneering how to measure the most popular GPTs! This has been super helpful. I have added the data on an ongoing basis to **GPT Search - the free public database and API of all GPTs**. I'll be adding comprehensive ratings, descriptions, and other stats that OpenAI is now providing so we can all get a full picture of the best GPTs.  I'm also psyched to add some data visualizations from the data so we can get insight from the data.

If it helps I am happy to contribute to this repo and add the additional stats I am pulling in from other sources. I am also happy to run the daily job from similarweb if that helps you control costs. LMK.

**App** - https://suefel.com/gpts
**API** - https://gpt-search-za6rvhzkqa-uc.a.run.app/docs
**GPT** - https://chat.openai.com/g/g-ob52WcUXC

![Screen Shot 2023-12-11 at 12 10 16 PM](https://github.com/1mrat/gpt-stats/assets/1211799/95882bb5-5bff-4c9f-8939-2ac49d442a2f)
![Screen Shot 2023-12-11 at 12 13 14 PM](https://github.com/1mrat/gpt-stats/assets/1211799/88e25032-2cb2-4447-8e7a-2fb48e9a6e9d)
![Screen Shot 2023-12-11 at 12 15 49 PM](https://github.com/1mrat/gpt-stats/assets/1211799/04c4c12e-78bf-4c29-9150-0fe53a55154b)

**Comment by casssapir** [comment]
Also added a simple repo like this one where you can quickly get a csv list of all gpts

https://github.com/casssapir/gpt-list

**Comment by voidSphere** [comment]
> I'll be adding comprehensive ratings, descriptions, and other stats that OpenAI is now providing 

OpenAI provides a rating?

**Comment by casssapir** [comment]
> > I'll be adding comprehensive ratings, descriptions, and other stats that OpenAI is now providing
> 
> OpenAI provides a rating?

Yes the Open AI GPT Store will have metrics around quality and popularity. Still TBD exactly what form. There are also a few dozen places where people have started organically rating GPTs on various lists, stores, and forums. We are aggregating these and normalizing them to provide a baseline rating for each GPT.

**Comment by 1mrat** [comment]
This is great - ill add a tools.md file to the repo to refer people out to your site and mention it in  the readme.

**Comment by 1mrat** [comment]
added
